#!/usr/bin/env python3

# SPDX-PackageName: dsari
# SPDX-PackageSupplier: Ryan Finnie <ryan@finnie.org>
# SPDX-PackageDownloadLocation: https://codeberg.org/rfinnie/dsari
# SPDX-FileCopyrightText: © 2015 Ryan Finnie <ryan@finnie.org>
# SPDX-License-Identifier: MPL-2.0

from pathlib import Path
from runpy import run_module
import sys

sys.path.insert(0, str(Path(__file__).resolve().parent))
run_module("dsari.prometheus_exporter", run_name="__main__")
